### ISSUE TITLE
The page will scroll abnormally to the bottom of the problem.

### ISSUE THREAD

**Issue by easyworks** [caroso1222/ngx-cool-dialogs#2]
In the angular5 environment, the page will scroll to the bottom after the dialog box pops up. angular4 is not tested.
Hope you can fix it as soon as possible!

**Comment by croso-df** [comment]
Hey @easyworks, thanks for the report. So, the repro steps are:
1. Create and Angular 5 app.
2. Add ngx-cool-dialogs
3. Open a dialog
4. Page will scroll down to bottom

Is that right? I'll investigate.

**Comment by caroso1222** [comment]
Hey @easyworks, thanks for the report. So, the repro steps are:

Create and Angular 5 app.
Add ngx-cool-dialogs
Open a dialog
Page will scroll down to bottom

Is that right? I'll investigate.

**Comment by easyworks** [comment]
Yes, that is it.

**Comment by easyworks** [comment]
Forgot to explain that my test environment is a mobile phone, webkit kernel.

**Comment by caroso1222** [comment]
I confirm that I can reproduce the issue now. Didn't catch it before as the demo is in full height mode. Let me fix this real quick and release a patch.

**Comment by caroso1222** [comment]
Hey @easyworks, I just deployed v0.1.3 with the patch. Let me know if this fixes the issue for you. If you still have trouble I'll reopen the issue.

Thanks again for taking the time to report the issue!
