### ISSUE TITLE
how to set default button in confirm?

### ISSUE THREAD

**Issue by chojuanillo** [caroso1222/ngx-cool-dialogs#5]
hello!. great component!. 
how can I put the default button to 'no'
thanks

**Comment by caroso1222** [comment]
Hey @chojuanillo, sorry for the delay. Rough week.

You can configure the library defaults by passing a [global config object](https://github.com/caroso1222/ngx-cool-dialogs#ngxcooldialogsglobalconfig) when importing the module with `forRoot`.

For this particular use case you want to use the `okButtonText` option as follows:
```typescript
imports: [
  BrowserAnimationsModule,
  BrowserModule,
  NgxCoolDialogsModule.forRoot({
    okButtonText: 'No'
  })
]
```

If you want to set the ok button to 'No' just once, then you will only have to use the [local config object](https://github.com/caroso1222/ngx-cool-dialogs#ngxcooldialogslocalconfig) when showing the modal:

```typescript
this.coolDialogs.confirm('Lorem Ipsum Dolor?', {
  okButtonText: 'No'
});
```
