### ISSUE TITLE
Have component as content

### ISSUE THREAD

**Issue by geoffhuntoon** [caroso1222/ngx-cool-dialogs#6]
Hello! 

The ngx-cool-dialogs are great! One question - is it possible to have a child component be the content of the dialog?

**Comment by caroso1222** [comment]
Hey @geoffhuntoon!

Thanks for opening this issue. At the moment, I don't have any plans of allowing custom templates inside of the dialog as I truly want to keep the API lightweight, just like `window.alert` and so on. 

For your particular use case, I suggest you consider using some of the [dialogs libraries](https://github.com/shlomiassaf/ngx-modialog) out there which are well suited to support custom templates.

**Comment by geoffhuntoon** [comment]
Fair enough - thank you for some great components!
